apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-api
  template:
    metadata:
      labels:
        app: ml-api
    spec:
      containers:
        - name: ml-api
          image: ml-api:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          #Zmienne środowiskowe z configmap
          env:
            - name: VERSION
              valueFrom:
                configMapKeyRef:
                  name: ml-api-config
                  key: APP_VERSION
            - name: DESCRIPTION
              valueFrom:
                configMapKeyRef:
                  name: ml-api-config
                  key: MODEL_DESCRIPTION

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"